# Generated by Django 6.1.1 on 2026-09-20 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='1–12')),
                ('year', models.IntegerField()),
                ('draw_type', models.CharField(choices=[('random', 'Random'), ('algorithmic', 'Algorithmic (weighted by score frequency)')], default='random', max_length=20)),
                ('drawn_numbers', models.JSONField(default=list, help_text='5 numbers drawn from Stableford range (1–45)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('simulated', 'Simulated'), ('published', 'Published')], default='pending', max_length=20)),
                ('total_prize_pool', models.DecimalField(decimal_places=2, default=0, help_text='Total GBP prize pool for this draw', max_digits=10)),
                ('active_subscriber_count', models.IntegerField(default=0, help_text='Snapshot of active subscriber count at draw time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'draw',
                'verbose_name_plural': 'draws',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DrawEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField(help_text="User's score snapshot at draw time")),
                ('matches', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='draws.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'draw entry',
                'verbose_name_plural': 'draw entries',
                'unique_together': {('draw', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PrizeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('five_match', '5 Match (Jackpot)'), ('four_match', '4 Match'), ('three_match', '3 Match')], max_length=20)),
                ('pool_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rollover_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('winner_count', models.IntegerField(default=0)),
                ('amount_per_winner', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_tiers', to='draws.draw')),
            ],
            options={
                'unique_together': {('draw', 'tier')},
            },
        ),
    ]
