# Generated by Django 6.1.1 on 2026-09-21 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draws', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='GBP amount this winner is entitled to', max_digits=10)),
                ('proof_image', models.ImageField(blank=True, help_text='Screenshot from the golf platform confirming scores', null=True, upload_to='winner_proofs/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='draws.draw')),
                ('prize_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='draws.prizetier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'winner',
                'verbose_name_plural': 'winners',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'draw')},
            },
        ),
    ]
