# Generated by Django 6.1.1 on 2026-09-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Primary charity image', null=True, upload_to='charities/')),
                ('website', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured charities appear on the homepage spotlight')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive charities are hidden from the directory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'charity',
                'verbose_name_plural': 'charities',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='charities.charity')),
            ],
            options={
                'verbose_name': 'charity event',
                'verbose_name_plural': 'charity events',
                'ordering': ['event_date'],
            },
        ),
    ]
